- id: https://osf.io/ukms6/resources
  type: paper

- id: url:https://osf.io/preprints/psyarxiv/8au9j_v1
  title: Horizontal information binds human face identity across views
  authors:
  - Alexia Roux-Sibilon
  - Helene Dumont
  - Vincent Bremhorst
  - Christianne Jacobs
  - Valerie Goffaux
  publisher: PsyArXiv
  date: '2025-06-13'
  link: https://osf.io/preprints/psyarxiv/8au9j_v1
  type: paper
  image: images/paper_images/ARS2025.png

- id: doi:10.31219/osf.io/z5qgk_v1
  type: paper
  image: images/paper_images/Grandjean_2025.png

- id: doi:10.1371/journal.pone.0311225
  type: paper
  image: images/paper_images/helene2024.PNG
  
- id: doi:10.1016/j.neuroimage.2023.120139
  type: paper
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1053811923002902-gr6.jpg

- id: doi:10.1371/journal.pone.0285255
  image: images/paper_images/2.PNG
  
- id: doi:10.1098/rspb.2023.1118
  image: images/paper_images/3.png

- id: doi:10.1523/ENEURO.0420-21.2022
  image: https://www.eneuro.org/content/eneuro/9/5/ENEURO.0420-21.2022/F1.large.jpg?width=800&height=600&carousel=1

- id: doi:10.1093/cercor/bhab238
  title: Coarse-to-Fine(r) Automatic Familiar Face Recognition in the Human Brain
  publisher: Cerebral Cortex
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/cercor/32/8/10.1093_cercor_bhab238/1/bhab238f4.jpeg?Expires=1690889959&Signature=R6LOZDk~KPxlLfpkKrHHHjEgng6eRlb9-wcCSnrLox9F4VVO1ClaYswwI9lW~xdBcJ~wEiQe5eTpfotxQxnKjnlZZI8Fvj-dJ~2RM9oeN-2sCDlBgye5mCScBFIJh9EwVe3W-s0PqzWz4fQIYvDGpROHj93jcNTfKmp3u1~dd52GPJEmkJA2bqWZFH-C8pOaNiXdW1E30DBEH5K8KCPfGJBmDnMETClv0bmT-03Ta1yXzqvgnvPHCF6Fdl1i5Vtv0IE2fLfDKmkIakHEaLtwMvlI4Xfx1d5fmtSht7ZwHoJYEaqZbAjwECnqhw18WHAdRzzsvq6RXtrC~Hjv0Ljmjw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  date: '2021-09-09'
  authors:
    - Xiaoqian Yan
    - Valérie Goffaux
    - Bruno Rossion
    
- id: doi:10.1109/MSP.2021.3120982
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/79/9664581/9664582/applications06-3120982-large.gif

- id: doi:10.1016/j.neuroimage.2021.118613
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1053811921008867-gr4.jpg

- id: doi:10.1371/journal.pone.0229185
  image: images/paper_images/8.png
  
- id: doi:10.1016/j.neuroimage.2018.10.086
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1053811918320706-fx1_lrg.jpg

- id: doi:10.1371/journal.pone.0210503
  image: images/paper_images/10.png
  
- id: doi:10.1016/j.neuroimage.2018.04.034
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1053811918303446-gr4.jpg

- id: doi:10.1038/s41598-018-30900-0
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41598-018-30900-0/MediaObjects/41598_2018_30900_Fig2_HTML.png?as=webp

- id: doi:10.1016/j.biopsycho.2018.07.009
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0301051118305684-gr3_lrg.jpg
  
- id: doi:10.1016/j.neuropsychologia.2015.12.004
  image: https://ars.els-cdn.com/content/image/1-s2.0-S002839321530244X-gr1_lrg.jpg

- id: doi:10.1038/srep34204
  image: images/paper_images/15.png

- id: doi:10.1002/dev.21396
  image: https://onlinelibrary.wiley.com/cms/asset/a530d786-42b2-4eca-817e-ef79ce1f242b/dev21396-fig-0001-m.jpg

- id: doi:10.1002/dev.21396
  image: https://onlinelibrary.wiley.com/cms/asset/a530d786-42b2-4eca-817e-ef79ce1f242b/dev21396-fig-0001-m.jpg

- id: doi:10.1038/srep21189
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fsrep21189/MediaObjects/41598_2016_Article_BFsrep21189_Fig1_HTML.jpg?as=webp

- id: doi:10.1016/j.actpsy.2015.11.007
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0001691815300792-gr2.jpg

- id: doi:10.1371/journal.pone.0138812
  image: images/paper_images/19.png
  
- id: doi:10.1167/14.2.5
  title: Face perception is tuned to horizontal orientation in the N170 time window
  publisher: Journal of Vision
  date: '2014-02-07'
  authors:
    - Corentin Jacques
    - Christine Schiltz
    - Valérie Goffaux
  image: https://arvo.silverchair-cdn.com/arvo/content_public/journal/jov/932814/i1534-7362-14-2-5-f03.jpeg?Expires=1690891702&Signature=4KM4A6sd09F3DSf00Pffrf5TRwp8ctCLEqPSmbLLPqvIngEmoFlwb4fBIPQWJ55QKVkSBCJ3BSnC6Yy8ReKCjLcQ3HhkoJ0lQYWkO5Cf2RYqbmiLbb~JJBEpv0nfO5-t~JpSLea72nW77VrAwsCQJ7UYbvhfDXYe~OlwfhZaGDdj9HBJQFhOTeUgmb6i0frSxSF-0Fy8WkJnQH7dxdjmmnsnRgoLCCDhM2ZbAe8cimZs7hRfU3tBtouP2~B9j19l1TKIVAh2QI8rNbWyNC2WNRgqYTKgm3CycRrTOsmO~UJMtCheov42OH~CuDDzguLH1wjGHddJbpSI~TmwFWRPQA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1080/20445911.2014.946419
  image: https://www.tandfonline.com/na101/home/literatum/publisher/tandf/journals/content/pecp21/2015/pecp21.v027.i04/20445911.2014.946419/20150427/images/large/pecp_a_946419_f0004a_oc.jpeg

- id: doi:10.3389/fpsyg.2012.00604
  image: https://www.frontiersin.org/files/Articles/36240/fpsyg-03-00604-HTML/image_m/fpsyg-03-00604-g003.jpg

- id: doi:10.1016/j.neuropsychologia.2012.09.046
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0028393212004186-gr2.jpg
  
- id: doi:10.1016/j.visres.2012.04.022
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0042698912001459-gr2.jpg

- id: doi:10.1167/11.10.1
  title: The horizontal tuning of face perception relies on the processing of intermediate and high spatial frequencies
  publisher: Journal of Vision
  date: '2011-09-06'
  authors:
    - Valérie Goffaux
    - Jaap van Zon
    - Christine Schiltz
  image: https://arvo.silverchair-cdn.com/arvo/content_public/journal/jov/932789/jov-11-10-1-fig001.jpeg?Expires=1690892596&Signature=BPZSCwwiBPSJu8FWrpG6J2hF3PctrhncEdzj4mhs8gJ9Le0wI1DZJvFzgu6oXPbhD6DItXoWsvcZwJLiLPQre-RU6DrFCN~hVmyBK7NvOvGCrdTIpA70pb061yY7h3wxIlK~~A6Bt4BiKjbB~pv7c5R4KDTVpp58ZG4KZkmPZ~9pBavTslkIgWOkCJrFOuu77g6vY~2R7-79g98xo65kuDHB01azck14AuiGf8MEr1srWl9ltdfNPBQIJLZ0AXLEwSqAXhsy2jd9i1DCZSj~0R5q5i13OBQDz8GgQE95iyLa2l4Zf5u~kHnHelvx9~KINGe-YaBAsSM9lLE6PSCdEw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1093/cercor/bhq112
  title: From Coarse to Fine? Spatial and Temporal Dynamics of Cortical Face Processing
  publisher: Cerebral Cortex
  date: '2010-06-24'
  authors:
    - Valérie Goffaux
    - Judith Peters
    - Christine Schiltz
    - Julie Haubrechts
    - Bernadette Jansma
    - Rainer Goebel
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/cercor/21/2/10.1093_cercor_bhq112/2/cercorbhq112f04_4c.jpeg?Expires=1690893001&Signature=0Bds1ma6~eZ0FG30rsSWQORNFh6IBsrlOmVXTFdG8dovCgWm9Hh1A0qF857lefMpjdz~YUAtLOhFVRoQFELYxaqLs-Qqy7P45JYxbW8nkWRAAsRzuh0ZsIzW8Mv7268HPtIB0zmHISbH9QTUXvuJP7d4I58o0nULl4TKnBQ5x~MfhXE~G~M9HZ7gVY9dCIIZK7uATUcWdkdSY47U3T6g0r0DZm~h2AVJKBKelLGalVJ6W28k3jDG3~GKbPpSUJiovONBSJ7kk-UXpDZo3avwnx-XP3lyylT587-yWXYjUBo~Vv9ZG6yr2RbpvztnN6LUGxpgMWtn4Gm1o8spFq8lHQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1162/jocn.2009.21320
  title: Characterizing the Spatio-temporal Dynamics of the Neural Events Occurring prior to and up to Overt Recognition of Famous Faces 
  publisher: Journal of Cognitive Neuroscience
  date: '2010-10-01'
  authors:
    - Boutheina Jemel
    - Anne-Marie Schuller
    - Valérie Goffaux
  image: images/paper_images/27.png

- id: doi:10.3389/fpsyg.2010.00143
  image: https://www.frontiersin.org/files/Articles/1721/fpsyg-01-00143-HTML/image_m/fpsyg-01-00143-g001.jpg

- id: doi:10.1167/9.5.12
  title: Is the early modulation of brain activity by fearful facial expressions primarily mediated by coarse low spatial frequency information?
  publisher: Journal of Vision
  date: '2009-05-14'
  authors:
    - Petra H. J. M. Vlamings
    - Valérie Goffaux
    - Chantal Kemner
  image: https://arvo.silverchair-cdn.com/arvo/content_public/journal/jov/932860/jov-9-5-12-fig001.jpeg?Expires=1690893644&Signature=cqp~d9rgBFkKN5RFVJeY2vWZGg-emLwCneMOxUJcB26FGvzsSfgbTNwSlzKvKVKJDwlNaqAXnPTQDRPQG5scScln2PCWaZaFDiLnjL29RInuKJXz-2tre8debgAOwEZDi1bohY4hbipUaA-wFiUjNUOWrWaBJzppZkukbWsdB2~4MbrjThR~M3sQp3sZSb-4KaveLVXR89WJ5tpy1PEnrvgH9dwj3Ex0mUNnO1bySX~5YYeqPoi2rGe~a~m1sRK~BgHV4MvcLy0kImY00xyzhohPktmwXtQ6DEKdbdcKCupNlhB0M2WA3jSA5jQqcYfNL9-KNp1WO6DmT960X0nsHQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1016/j.visres.2009.02.009
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0042698909000534-gr1.jpg

- id: doi:10.1348/174866408X292670
  image: https://bpspsychub.onlinelibrary.wiley.com/cms/asset/e39d0493-ae92-493a-8303-cb58b1f9f0e6/jnp_45_f2.gif

- id: doi:10.1016/j.actpsy.2007.11.005
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0001691807001345-gr1.jpg

- id: doi:10.1016/j.actpsy.2007.11.005
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0001691807001345-gr1.jpg

- id: doi:10.1016/j.cognition.2006.12.012
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0010027706002678-gr2.jpg

- id: doi:10.1037/0096-1523.33.4.995
  image: images/paper_images/34.png

- id: doi:10.1162/jocn.2007.19.3.543
  title: Long-term Expertise with Artificial Objects Increases Visual Competition with Early Face Categorization Processes
  publisher: Journal of Cognitive Neuroscience
  date: '2007-03-01'
  authors:
    - Bruno Rossion
    - Daniel Collins
    - Valérie Goffaux
    - Tim Curran
  image: images/paper_images/35.png

- id: doi:10.1037/0096-1523.32.4.1023
  image: images/paper_images/36.png

- id: doi:10.1080/13506280444000562
  image: images/paper_images/37.png

- id: doi:10.1068/p5370
  image: images/paper_images/38.png

- id: doi:10.1016/j.neulet.2003.09.029
  image: https://ars.els-cdn.com/content/image/1-s2.0-S030439400301111X-gr1.jpg

- id: pmid:14600493
  image: images/paper_images/40.jpeg

- id: doi:10.1016/S0926-6410(03)00056-9
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0926641003000569-gr1.jpg

- id: doi:10.1207/s15516709cog2702_8
  image: images/paper_images/42.png
  
- id: doi:10.1111/1467-9280.00446
  image: images/paper_images/43.png

- id: doi:10.1016/S0301-0511(99)00013-7
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0301051199000137-gr4.jpg
